export CUDA_VISIBLE_DEVICES=0

model_name=VLBM

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/SOLAR/ \
  --data_path solar_Alabama.csv \
  --model_id solar_96_12 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 256 \
  --num_Period_Block 4 \
  --m 400 \
  --interval 15 \
  --heads 4 \
  --use_norm 0 \
  --learning_rate 0.0005 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --batch_size 16 \
  --train_epochs 30 \
  --itr 1 \
  --target "PV137" \

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/SOLAR/ \
  --data_path solar_Alabama.csv \
  --model_id solar_96_96 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 128 \
  --num_Period_Block 2 \
  --m 100 \
  --interval 15 \
  --heads 4 \
  --use_norm 1 \
  --learning_rate 0.001 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --batch_size 16 \
  --train_epochs 10 \
  --patience 1 \
  --itr 1 \
  --target "PV137" \

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/SOLAR/ \
  --data_path solar_Alabama.csv \
  --model_id solar_96_336 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 336 \
  --hiddens 256 \
  --num_Period_Block 4 \
  --m 400 \
  --interval 15 \
  --heads 4 \
  --use_norm 0 \
  --learning_rate 0.0005 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --batch_size 16 \
  --train_epochs 30 \
  --itr 1 \
  --target "PV137" \

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/SOLAR/ \
  --data_path solar_Alabama.csv \
  --model_id solar_96_720 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 720 \
  --hiddens 256 \
  --num_Period_Block 1 \
  --m 50 \
  --interval 15 \
  --heads 4 \
  --use_norm 1 \
  --learning_rate 0.0005 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --batch_size 16 \
  --train_epochs 30 \
  --itr 1 \
  --target "PV137"