export CUDA_VISIBLE_DEVICES=0

model_name=VLBM

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/Flight/ \
  --data_path Flight.csv \
  --model_id Flight_96_12 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 256 \
  --num_Period_Block 1 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.0003 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --batch_size 16 \
  --target 'UUEE' \
  --train_epochs 20 \
  --patience 20 \
  --lradj cosine \
  --itr 1

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/Flight/ \
  --data_path Flight.csv \
  --model_id Flight_96_96 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.0003 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --batch_size 16 \
  --target 'UUEE' \
  --train_epochs 20 \
  --patience 20 \
  --lradj cosine \
  --itr 1

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/Flight/ \
  --data_path Flight.csv \
  --model_id Flight_96_336 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 336 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.0003 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --batch_size 16 \
  --target 'UUEE' \
  --train_epochs 20 \
  --patience 20 \
  --lradj cosine \
  --itr 1

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/Flight/ \
  --data_path Flight.csv \
  --model_id Flight_96_720 \
  --model $model_name \
  --data vlbm \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 720 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.0003 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --batch_size 16 \
  --target 'UUEE' \
  --train_epochs 20 \
  --patience 20 \
  --lradj cosine \
  --itr 1