export CUDA_VISIBLE_DEVICES=0

model_name=VLBM

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS03/ \
  --data_path PEMS03.npz \
  --model_id PEMS_96_12 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS03/ \
  --data_path PEMS03.npz \
  --model_id PEMS_96_24 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 24 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS03/ \
  --data_path PEMS03.npz \
  --model_id PEMS_96_48 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 48 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS03/ \
  --data_path PEMS03.npz \
  --model_id PEMS_96_96 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0


python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS04/ \
  --data_path PEMS04.npz \
  --model_id PEMS_96_12 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS04/ \
  --data_path PEMS04.npz \
  --model_id PEMS_96_24 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 24 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS04/ \
  --data_path PEMS04.npz \
  --model_id PEMS_96_48 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 48 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS04/ \
  --data_path PEMS04.npz \
  --model_id PEMS_96_96 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS07/ \
  --data_path PEMS07.npz \
  --model_id PEMS_96_12 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 128 \
  --num_Period_Block 1 \
  --m 50 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.001 \
  --enc_in 883 \
  --dec_in 883 \
  --c_out 883 \
  --des 'Exp' \
  --batch_size 8 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS07/ \
  --data_path PEMS07.npz \
  --model_id PEMS_96_24 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 24 \
  --hiddens 128 \
  --num_Period_Block 1 \
  --m 50 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.001 \
  --enc_in 883 \
  --dec_in 883 \
  --c_out 883 \
  --des 'Exp' \
  --batch_size 8 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS07/ \
  --data_path PEMS07.npz \
  --model_id PEMS_96_48 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 48 \
  --hiddens 128 \
  --num_Period_Block 1 \
  --m 50 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.001 \
  --enc_in 883 \
  --dec_in 883 \
  --c_out 883 \
  --des 'Exp' \
  --batch_size 8 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS07/ \
  --data_path PEMS07.npz \
  --model_id PEMS_96_96 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 128 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 1 \
  --learning_rate 0.001 \
  --enc_in 883 \
  --dec_in 883 \
  --c_out 883 \
  --des 'Exp' \
  --batch_size 8 \
  --itr 1 \
  --use_norm 0


python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS08/ \
  --data_path PEMS08.npz \
  --model_id PEMS_96_12 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 12 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS08/ \
  --data_path PEMS08.npz \
  --model_id PEMS_96_24 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 24 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS08/ \
  --data_path PEMS08.npz \
  --model_id PEMS_96_48 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 48 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0

python -u run_vlbm.py \
  --task_name long_term_forecast_vlbm \
  --is_training 1 \
  --root_path ./raw_files/PEMS08/ \
  --data_path PEMS08.npz \
  --model_id PEMS_96_96 \
  --model $model_name \
  --data pems_vlbm_v1 \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --hiddens 256 \
  --num_Period_Block 2 \
  --m 200 \
  --interval 5 \
  --heads 4 \
  --learning_rate 0.001 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1 \
  --use_norm 0 \